### ISSUE TITLE
Should we use h3-r or h3forr?

### ISSUE THREAD

**Issue by riazarbi** [crazycapivara/h3-r#18]
Hello,

We're using `h3forr` in several projects. It's working really well, but for some of our faster code the library is a bit of a speed bottleneck. No complaints, it's working great otherwise. 

It occurs to me that this library might perform significantly faster than `h3forr`. Would this be the case? Our most used functions are `k-ring`, `polyfill` and parent-child operations.

Are there any other reasons to adopt one over the other? Which do you see as being better supported going forward?

**Comment by crazycapivara** [comment]
Hi,

`h3forr` has some overhead due to the `V8` engine. while `h3-r` uses the H3 C bindings directly.
Therefore, regarding performance you should use `h3-r`.

At the moment I also put more support in `h3-r`.

But I am not sure if it will work on windows in the future #3. That might be a reason to use `h3forr`!?

**Comment by riazarbi** [comment]
Thanks for the feedback; I'll move over to `h3-r`
